:toc: left
== Projetos de PDI
Powered by Felipe Omar and Weny Vasconcelos (C) 2017

Seja bem vindo(a)! Aqui você pode encontrar todos os projetos desenvolvidos e em desenvolvimento por nós na disciplina de *Processamento Digital de Imagens*, promovida pelo Departamento de Computação e Automação, Centro de Tecnologia, Universidade Federal do Rio Grande do Norte.


=== 1ª Atividade: link:negativo/negativo.html[Negativo de uma imagem].

Região de imagens sendo negativadas por interação do usuário.

=== 2ª Atividade: link:trocatroca/trocatroca.html[Troca regiões].

Trocando regiões da imagem, utilizando funções da biblioteca OpenCV.

=== 3ª Atividade: link:bolhas/bolhas.html[Identificando Bolhas].

Foi implementado um algoritmo que identificasse objetos presentes em uma imagem, contando e verificando quais destes continham "buracos", utilizando a função FloodFill do OpenCV. 

=== 4ª Atividade: [Equalizador de histograma]

A atividade propõe equalizar o histograma de uma imagem (em tempo real) utilizando uma webcam. O programa retorna uma janela com a imagem com seus níveis equalizados.

=== 5ª Atividade: [Detector de Movimento]

A tarefa utiliza de uma comparação entre histogramas atual e anterior a fim de visualizar se houve movimentação de acordo com as mudanças de níveis.

=== 6ª Atividade: [Filtragem Espacial]

Aperfeiçoamos um algoritmo mostrado pelo professor para que este acrescente o cálculo do laplaciando do gaussiano às imagens capturadas, comparando-o com o resultado do filtro laplaciano apenas.

=== 7ª Atividade: [Tilt-Shift]

É possível simular miniaturas com imagens e filmes em tamanho real. Esta técnica é chamada de Tilt-Shift. 